name: Push image

run-name: Push image ${{ github.ref }}

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build typescript
        working-directory: img-resizer
        run: |
          npm install
          npm run build
      - name: build image
        run: .github/workflows/scripts/build-image.sh
      - name: push image
        run: cat .github/workflows/scripts/build-image.sh

